version: "3.2"

services:
  backend:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=iamyourfatherluke
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  frontend:
    build: ./client
    volumes:
      - ./client:/client
      # One-way volume to use node_modules from inside image
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9000:8080"
